version: '3'
services:
  wordpress:
    image: wordpress
    ports:
      - 8081:80
    environment:
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_HOST=wp_db
    links:
      - wordpress_db:wp_db

  wordpress_db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3308:3306
    volumes:
      - /doc/wordpress_db:/var/lib/mysql
