version: '3'
services:
  service1:
    image: wordpress
    ports:
      - 8080:80
    environment:
      - WORDPRESS_DB_PASSWORD=example
      - WORDPRESS_DB_HOST=wp_db
    links:
      - wordpress_db:wp_db

  service2:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=example
    ports:
      - 3307:3306
    volumes:
      - /doc/wordpress_db:/var/lib/mysql
